# Generated by Django 3.1.5 on 2021-02-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.TextField()),
                ('bad', models.TextField()),
                ('ideas', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date sent')),
            ],
        ),
    ]
