# Generated by Django 3.1.5 on 2021-02-18 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rate',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
