# Generated by Django 3.1.5 on 2021-02-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='rate',
            new_name='grade',
        ),
    ]
