# Generated by Django 3.1.5 on 2021-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210218_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='topic',
            field=models.CharField(choices=[(1, 'Ruoka'), (2, 'Palvelu'), (3, 'Muu')], default='0', max_length=1),
        ),
    ]
