# Generated by Django 3.1.5 on 2021-02-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_auto_20210225_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (1, '2'), (3, '3'), (4, '4'), (5, '5')], default='1'),
        ),
    ]
