# Generated by Django 3.1.5 on 2021-03-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_auto_20210226_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField(choices=[(1, 'Ruoka'), (2, 'Palvelu'), (3, 'Muu')], default='1')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='topic',
        ),
    ]
