# Generated by Django 3.1.5 on 2021-03-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_auto_20210301_0813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackTopic',
        ),
        migrations.AddField(
            model_name='feedback',
            name='topic',
            field=models.IntegerField(choices=[(1, 'Ruoka'), (2, 'Palvelu'), (3, 'Muu')], default='1'),
        ),
    ]
