# Generated by Django 3.1.5 on 2021-03-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_auto_20210301_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
