# Generated by Django 3.1.5 on 2021-03-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_feedbacktopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='topic',
            field=models.IntegerField(choices=[(1, 'Ruoka'), (2, 'Palvelu'), (3, 'Muu')], null=True),
        ),
    ]
